/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jGetSite;

import java.awt.Component;

import java.util.List;
import javax.swing.*;
import javax.swing.ImageIcon;
import java.awt.*;
import java.util.ArrayList;
import java.awt.image.BufferedImage;
/**
 *
 * @author user
 */

class IconListCellRenderer extends JPanel implements ListCellRenderer<Website> {
    
    private final JLabel lblIcon = new JLabel();
    private final JLabel lblDesc = new JLabel();
    private final Color textSelectionColor = Color.BLACK;
    private final Color backgroundSelectionColor = Color.YELLOW;
    private final Color textNonSelectionColor = Color.BLACK;
    private final Color backgroundNonSelectionColor = Color.WHITE;
  
    
    IconListCellRenderer() {
        setLayout(new BorderLayout(5,5));
        JPanel panelText = new JPanel(new GridLayout(0,1));
        panelText.add(lblDesc);
        add(lblIcon, BorderLayout.WEST);
        add(panelText,BorderLayout.CENTER); 
    }
    
    @Override 
    public Component getListCellRendererComponent(
            JList list,
            Website website,
            int index,
            boolean selected,
            boolean expanded ){
        
        lblIcon.setIcon(new ImageIcon(website.getImage()));
        lblDesc.setText(website.getTitle());
        lblIcon.setOpaque(true);
        lblDesc.setOpaque(true);

        if (selected) {
            lblIcon.setBackground(backgroundSelectionColor);
            lblDesc.setBackground(backgroundSelectionColor); 
            setBackground(list.getSelectionBackground());
            
        } else {
            lblIcon.setBackground(backgroundNonSelectionColor);
            lblDesc.setForeground(textNonSelectionColor);
            lblDesc.setBackground(backgroundNonSelectionColor);
            setBackground(backgroundNonSelectionColor);
        }

        return this;
    }
            
}

public class IView extends javax.swing.JFrame {
    
  private IconListCellRenderer renderer = new IconListCellRenderer();
  private List<Website> webSiteList = new ArrayList<>();
  DefaultListModel<Website> imagemodel = new DefaultListModel<>();
  
    /**
     * Creates new form IView
     */
    public IView() {
        initComponents();
        setLocationRelativeTo(null); //Center form on screen
    }
    public void displayIcons(List<Website> listofwebsites) {
        webSiteList = listofwebsites;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        butLoadImages = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listIcons = new javax.swing.JList<Website>();

        setTitle("Web Page Icons");

        jLabel1.setText("Search For:");

        jScrollPane2.setViewportView(jTextPane1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        butLoadImages.setText("Load Images");
        butLoadImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoadImagesActionPerformed(evt);
            }
        });

        listIcons.setModel(imagemodel);
        jScrollPane3.setViewportView(listIcons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butLoadImages, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(butLoadImages))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butLoadImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoadImagesActionPerformed
        
        BufferedImage img = null;
        
        
        for (Website s: webSiteList ) {  
            if (s.getActive() && s.getImageFile() != null) {
             imagemodel.addElement(s);
               
            }   
        }
        
        listIcons.setCellRenderer(new IconListCellRenderer());
        listIcons.setModel(imagemodel);
    }//GEN-LAST:event_butLoadImagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLoadImages;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList<Website> listIcons;
    // End of variables declaration//GEN-END:variables
}
